# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "Year", # <codex_cert>
  "V1", # <codex_icd10>
  "V2", # <codex_icd10>
  "quarter_begin_date", # <codex_mue>
  "quarter_begin_date", # <codex_ptp>
  "effective_date", # <codex_ptp>
  "deletion_date", # <codex_ptp>
  "modifier_use", # <codex_ptp>
  "kg", # <bmi_adult>
  "cm", # <bmi_adult>
  "m", # <bmi_adult>
  NULL
))
